version: 2.1

orbs:
  docker: circleci/docker@1.0.1

jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - checkout
      - setup_remote_docker
      - docker/check
      - docker/build:
          image: akuritsyn/$CIRCLE_PROJECT_REPONAME
      - docker/push:
          digest-path: /tmp/digest.txt
          image: akuritsyn/$CIRCLE_PROJECT_REPONAME
          tag: 'latest'
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"

workflows:
  commit:
    jobs:
      - build-and-push:
          filters:
            branches:
              only:
                - master
          context: DockerHub